### ISSUE TITLE
Awesome tutorial !

### ISSUE THREAD

**Issue by MyElectricSheep** [simplecode-io/simple-api#2]
Hey simplecode !

This tutorial series was awesome :) I learnt a great deal following through it (and retyping every line of code to make sure I really understood what was going on!).

When's the next part coming up ? :smiley:

Best,

Ben

**Comment by simplecode-io** [comment]
Thanks Ben! That is very kind of you and that is awesome it helped you out! That is what we want to hear :smiley: 

We are working on another series for the front end right now and we will eventually tie to the two series together for one big applicaiton :) But what would you like the next part to be? 

Regards,

Owen

**Comment by MyElectricSheep** [comment]
Noted, thanks for the reply :) ! 

For the front-end, it would be great to dig into some React-Redux wizardry (one of the top skills asked by recruiters around here) ! For the tie-up, I guess it would be nice to see how to use the access tokens we created in the back-end tutorial to login using the front-end and access protected routes :)

Thanks and best,

Ben
